[[redirects]]
  from = "/2.0/stimulus-controllers.html"
  to = "/2.0/custom-fields.html#use-pre-built-stimulus-controllers"
  status = 301
  force = false

[[redirects]]
  from = "/0.1/*"
  to = "https://v1-docs.avohq.io/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/1.0/fields-reference.html"
  to = "https://v1-docs.avohq.io/1.0/field-options.html"
  status = 301
  force = false
